controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["base_left_wheel_joint"]
    right_wheel_names: ["base_right_wheel_joint"]
    
    wheel_separation: 0.32
    wheel_radius: 0.07
    
    use_stamped_vel: false
    cmd_vel_timeout: 0.5
    invert_angular_velocity: false
    
    # Frames
    base_frame_id: base_footprint
    odom_frame_id: odom
    
    # CRITICAL: These control TF publishing
    publish_odom: true           # Publish odom topic
    open_loop: false
    enable_odom_tf: true
    publish_tf: false

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        min_velocity: -2.0
