ekf_filter_node:
  ros__parameters:
    frequency: 15.0
    two_d_mode: true
    publish_tf: false
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_footprint"
    world_frame: "odom"

    odom0: "diff_drive_controller/odom"
    odom0_config: [false, false, false,
                   false,  false, true,
                   true, true, false,
                   false, false, true,
                   false, false, false]

    #imu0: "imu/data"
    #imu0_config: [false, false, false,
    #              false, false, false,
    #              false, false, false,
    #              false,  false, true,
    #              true, true, false]